# fly.toml app configuration file generated for cookierun-tcg-discord-bot on 2024-03-06T23:23:09-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cookierun-tcg-discord-bot'
primary_region = 'sea'

[build]

[http_service]
auto_start_machines = true 
auto_stop_machines = false # prevent automatic suspension
force_https = true 
internal_port = 8080 
min_machines_running = 1 # keep a machine running at all times
processes = ['app'] 

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
